version: '3.1'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=https://deployservertest.herokuapp.com/
    ports:
      - 80:80
